config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    put 'help', on: :member
    put 'answer', on: :member
    put 'take_money', on: :member
  end

  resource :questions, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :validatable, :rememberable

  validates :name, presence: true
  validates :is_admin, inclusion: {in: [true,false]}, allow_nil: false
  validates :balance, numericality: {only_integer: true}, allow_nil: false

  has_many :games, dependent: :destroy

  # расчёт среднего выигрыша по всем играм юзера
  def average_prize
    (balance.to_f/games.count).round unless games.count.zero?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all.order(balance: :desc)
  end

  def show
    @games = @user.games.order(created_at: :desc)
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/_game.html.erb
<%# Шаблон, который выводит информацию о конкретной игре для профиля пользователя %>
<tr class="text-center">
  <td><%= game.id %></td>
  <td><%= game_label(game) %></td>
  <td><%= l game.created_at, format: :short %></td>
  <td><%= game.current_level %></td>
  <td><%= number_to_currency game.prize %></td>
  <td>
    <%= content_tag :span, '50/50',
                    class: "label label-primary #{'game-help-used' if game.fifty_fifty_used?}"
    %>
    <%= content_tag :span, fa_icon('phone'),
                    class: "label label-primary #{'game-help-used' if game.friend_call_used?}"
    %>
    <%= content_tag :span, fa_icon('users'),
                    class: "label label-primary #{'game-help-used' if game.audience_help_used?}"
    %>
  </td>
</tr>

app/views/users/index.html.erb
<h1>Рейтинг</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <table class="users-table table">
      <thead>
      <tr>
        <th class="text-center">Место</th>
        <th class="text-center">Имя</th>
        <th class="text-center">Выигрыш</th>
        <th class="text-center">Игр</th>
        <th class="text-center">За игру</th>
      </tr>
      </thead>

      <%# Для каждого пользователя выводим информацию о его выигрыше, ссылку на профиль и так далее %>
      <% @users.each_with_index do |user, index| %>
        <tr class="text-center">
          <td><%= index + 1 %></td>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= number_to_currency user.balance %></td>
          <td><%= user.games.count %></td>
          <td><%= user.average_prize %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div>
      <h1><%= @user.name %></h1>
      <%= link_to 'Сменить имя и пароль', edit_user_registration_path(@user) if @user == current_user %>
    </div>
    <table class="users-table table">
      <thead>
      <tr>
        <th class="text-center">#</th>
        <th></th>
        <th class="text-center">Дата</th>
        <th class="text-center">Вопрос</th>
        <th class="text-center">Выигрыш</th>
        <th class="text-center">Подсказки</th>
      </tr>
      </thead>

      <%# Выводим список игр пользователя с помощью нашего фрагмента users/_game %>
      <%= render partial: 'game', collection: @games %>
    </table>
  </div>
</div>